# Generated by Django 5.2.4 on 2025-07-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('polera_hombre', 'Polera Hombre'), ('polera_mujer', 'Polera Mujer'), ('short', 'Short'), ('falda', 'Falda'), ('poleron', 'Polerón')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('metros_tela', models.FloatField()),
                ('stock', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
