# Generated by Django 5.2.4 on 2025-07-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_teladisponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.color'),
        ),
        migrations.AlterField(
            model_name='teladisponible',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.color'),
        ),
    ]
